// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2083.TeamBlitzRobot2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSystemWheelMotor1;
    public static SpeedController gripperMotorController1;
    public static SpeedController gripperMotorController2;
    public static SpeedController fourBarLifterLinearActuator;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystemWheelMotor1 = new Talon(0);
        LiveWindow.addActuator("Drive System", "Wheel Motor 1", (Talon) driveSystemWheelMotor1);
        
        gripperMotorController1 = new Talon(1);
        LiveWindow.addActuator("Gripper", "Motor Controller 1", (Talon) gripperMotorController1);
        
        gripperMotorController2 = new Talon(2);
        LiveWindow.addActuator("Gripper", "Motor Controller 2", (Talon) gripperMotorController2);
        
        fourBarLifterLinearActuator = new Talon(3);
        LiveWindow.addActuator("Four Bar Lifter", "Linear Actuator", (Talon) fourBarLifterLinearActuator);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
