// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2083.TeamBlitzRobot2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {

    public static final int leftForwardMotor = 5;
    public static final int leftBackMotor = 3;
    public static final int rightForwardMotor = 2;
    public static final int rightBackMotor = 12;

    public static CANJaguar leftFront;
    public static CANJaguar leftBack;
    public static CANJaguar rightFront;
    public static CANJaguar rightBack;

    public static int downButton = 4;
    public static int upButton = 3;
    public static int openButton = 2;
    public static int closeButton = 1;

    public static boolean auto = false;
    public static double autoX = 0;
    public static double autoY = 0;
    public static boolean autoDown = true;
    public static boolean autoUp = false;
    public static boolean autoOpen = false;
    public static boolean autoClose = false;
    public static double autoTimer = -1;
    
    public static double leftOffset = -1;
    public static double rightOffset = -1;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController rightDriveSubsystemRightFrontMotor;
    public static SpeedController rightDriveSubsystemRightRearMotor;
    public static SpeedController gripperLeftMotorController;
    public static SpeedController gripperRightMotorController;
    public static SpeedController fourBarLifterLinearActuator;
    public static SpeedController leftDriveSubsystemLeftFrontMotor;
    public static SpeedController leftDriveSubsystemLeftRearMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightDriveSubsystemRightFrontMotor = new Talon(0);
        LiveWindow.addActuator("Right Drive Subsystem", "Right Front Motor", (Talon) rightDriveSubsystemRightFrontMotor);
        
        rightDriveSubsystemRightRearMotor = new Talon(6);
        LiveWindow.addActuator("Right Drive Subsystem", "Right Rear Motor", (Talon) rightDriveSubsystemRightRearMotor);
        
        gripperLeftMotorController = new Talon(1);
        LiveWindow.addActuator("Gripper", "Left Motor Controller", (Talon) gripperLeftMotorController);
        
        gripperRightMotorController = new Talon(2);
        LiveWindow.addActuator("Gripper", "Right Motor Controller", (Talon) gripperRightMotorController);
        
        fourBarLifterLinearActuator = new Talon(3);
        LiveWindow.addActuator("Four Bar Lifter", "Linear Actuator", (Talon) fourBarLifterLinearActuator);
        
        leftDriveSubsystemLeftFrontMotor = new Talon(4);
        LiveWindow.addActuator("Left Drive Subsystem", "Left Front Motor", (Talon) leftDriveSubsystemLeftFrontMotor);
        
        leftDriveSubsystemLeftRearMotor = new Talon(5);
        LiveWindow.addActuator("Left Drive Subsystem", "Left Rear Motor", (Talon) leftDriveSubsystemLeftRearMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
