// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2083.TeamBlitzRobot2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController rightDriveSubsystemRightFrontMotor;
    public static SpeedController rightDriveSubsystemRightRearMotor;
    public static SpeedController gripperLeftMotorController;
    public static SpeedController gripperRightMotorController;
    public static SpeedController fourBarLifterLinearActuator;
    public static SpeedController leftDriveSubsystemLeftFrontMotor;
    public static SpeedController leftDriveSubsystemLeftRearMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightDriveSubsystemRightFrontMotor = new Jaguar(1);
        LiveWindow.addActuator("Right Drive Subsystem", "Right Front Motor", (Jaguar) rightDriveSubsystemRightFrontMotor);
        
        rightDriveSubsystemRightRearMotor = new Jaguar(8);
        LiveWindow.addActuator("Right Drive Subsystem", "Right Rear Motor", (Jaguar) rightDriveSubsystemRightRearMotor);
        
        gripperLeftMotorController = new Jaguar(5);
        LiveWindow.addActuator("Gripper", "Left Motor Controller", (Jaguar) gripperLeftMotorController);
        
        gripperRightMotorController = new Jaguar(2);
        LiveWindow.addActuator("Gripper", "Right Motor Controller", (Jaguar) gripperRightMotorController);
        
        fourBarLifterLinearActuator = new Talon(0);
        LiveWindow.addActuator("Four Bar Lifter", "Linear Actuator", (Talon) fourBarLifterLinearActuator);
        
        leftDriveSubsystemLeftFrontMotor = new Jaguar(2);
        LiveWindow.addActuator("Left Drive Subsystem", "Left Front Motor", (Jaguar) leftDriveSubsystemLeftFrontMotor);
        
        leftDriveSubsystemLeftRearMotor = new Jaguar(7);
        LiveWindow.addActuator("Left Drive Subsystem", "Left Rear Motor", (Jaguar) leftDriveSubsystemLeftRearMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
